services:
  webalert-frontend-dev:
    container_name: webalert-frontend-dev
    image: webalert:frontend-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        VITE_VUE_APP_API_BASE_URL: "http://localhost:8000/api/"
    ports:
      - "80:80"
    networks:
      - webalert-network
    profiles: [ dev ]   

networks:
  webalert-network:
    name: webalert-network
    external: true